post http://localhost:8080/unauth/auth
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test1"
}

#########################################

post http://localhost:8080/auth/out
Cookie: Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlcyI6bnVsbCwiaXNzIjoiYXBpX3Rva2VuIiwiZXhwIjoxNjU3ODM4MTY1LCJpYXQiOjE2NTc4MzQ1NjV9.bi3StLbsF7ygUM0mj-I9M4ZYR4q79_J62_ACb1NfIjo; Max-Age=3600000000000; HttpOnly