server: 
  port: "8080"
  host: "localhost"
  timeOutSEc: 10

mysql:
    username: "root"
    host: "localhost"
    port: "3306"
    dbname: "jobhunter"
    protocol: "tcp"
    options: "parseTime=true"

postgres:
    username: "postgres"
    host: "localhost"
    port: "5436"
    dbname: "postgres"
    options: ""