-- MySQL Script generated by MySQL Workbench
-- Mon Jul 11 23:33:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jobH
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobH` ;

-- -----------------------------------------------------
-- Schema jobH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobH` ;
USE `jobH` ;

-- -----------------------------------------------------
-- Table `jobH`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobH`.`Role` ;

CREATE TABLE IF NOT EXISTS `jobH`.`Role` (
  `idRole` INT NOT NULL,
  `name` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `Rolecol_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobH`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobH`.`User` ;

CREATE TABLE IF NOT EXISTS `jobH`.`User` (
  `idUser` INT NOT NULL,
  `login` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `dateCreated` TIMESTAMP NOT NULL,
  `password` BINARY(60) NOT NULL,
  `lastCheck` TIMESTAMP NOT NULL,
  `fullName` VARCHAR(150) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobH`.`User_has_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobH`.`User_has_Role` ;

CREATE TABLE IF NOT EXISTS `jobH`.`User_has_Role` (
  `User_idUser` INT NOT NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Role_idRole`),
  INDEX `fk_User_has_Role_Role1_idx` (`Role_idRole` ASC) VISIBLE,
  INDEX `fk_User_has_Role_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Role_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `jobH`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Role_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `jobH`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
