openapi: 3.0.1
info:
  title: Swagger Example API
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  contact: {}
  version: "1.0"
servers:
- url: //localhost:8080/
paths:
  /auth:
    post:
      tags:
      - auth
      summary: Authorization
      description: if user exists sets cookie with JWT token
      requestBody:
        description: Email and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.AuthInfo'
        required: true
      responses:
        200:
          description: Message and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.Token'
                  model.JSONResult:
                    $ref: '#/components/schemas/model.JSONResult'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.JSONResult'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.JSONResult'
      x-codegen-request-body-name: authInfo
  /reg:
    post:
      tags:
      - auth
      summary: Registration
      description: creates new user if unique login and email
      requestBody:
        description: Login, email, password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.NewUser'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.JSONResult'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.JSONResult'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.JSONResult'
      x-codegen-request-body-name: newUser
components:
  schemas:
    model.AuthInfo:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          default: test@test.com
        password:
          maxLength: 40
          minLength: 5
          type: string
          default: test1
    model.JSONResult:
      type: object
      properties:
        data:
          type: object
        message:
          type: string
    model.NewUser:
      required:
      - cPassword
      - email
      - login
      - password
      - roles
      type: object
      properties:
        cPassword:
          maxLength: 40
          minLength: 5
          type: string
          default: test1
        email:
          type: string
          default: test@test.com
        login:
          maxLength: 40
          minLength: 3
          type: string
          default: test
        password:
          type: string
          default: test1
        roles:
          type: array
          items:
            type: string
    model.Token:
      type: object
      properties:
        token:
          type: string
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT